# Generated by Django 4.2.16 on 2024-09-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('featured', models.BooleanField(default=False)),
                ('description', models.TextField(max_length=1000)),
                ('gitImage', models.FileField(blank=True, null=True, upload_to='images/')),
                ('gitLink', models.URLField(blank=True, null=True, verbose_name='Git Project Link')),
            ],
        ),
    ]
