# Generated by Django 4.2.16 on 2024-10-01 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_alter_projects_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('mainImage', models.FileField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleData',
            fields=[
                ('step', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('heading', models.CharField(max_length=250)),
                ('image', models.FileField(blank=True, null=True, upload_to='images/')),
                ('description', models.TextField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articleData', to='backend_api.article')),
            ],
        ),
    ]
