# Generated by Django 4.2.16 on 2024-10-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_article_articledata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articledata',
            options={'verbose_name_plural': 'Articles Data'},
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
