# Generated by Django 4.2.16 on 2024-10-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0004_alter_articledata_options_alter_article_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='articledata',
            name='id',
            field=models.BigAutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articledata',
            name='step',
            field=models.IntegerField(),
        ),
    ]
