# Generated by Django 4.2.16 on 2024-10-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0005_articledata_id_alter_articledata_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='created_date',
            field=models.DateField(auto_now=True),
        ),
    ]
